# Generated by Django 3.2.3 on 2022-08-08 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoredPduData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTime', models.DateTimeField(auto_now_add=True)),
                ('outputNum', models.IntegerField()),
                ('current', models.DecimalField(decimal_places=2, max_digits=20)),
                ('power', models.DecimalField(decimal_places=2, max_digits=20)),
                ('energyCounter', models.DecimalField(decimal_places=2, max_digits=20)),
                ('tpf', models.DecimalField(decimal_places=2, max_digits=20)),
                ('phaseShift', models.DecimalField(decimal_places=2, max_digits=20)),
                ('reverseEnergyCounter', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
    ]
