# Generated by Django 3.2.3 on 2022-08-10 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('env', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Camera',
        ),
        migrations.DeleteModel(
            name='Co2',
        ),
        migrations.DeleteModel(
            name='Humidity',
        ),
        migrations.DeleteModel(
            name='Light',
        ),
        migrations.DeleteModel(
            name='Motor',
        ),
        migrations.DeleteModel(
            name='Temperature',
        ),
    ]
