# Generated by Django 3.2.3 on 2022-08-10 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('env', '0002_auto_20220810_1315'),
    ]

    operations = [
        migrations.CreateModel(
            name='CameraData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rackNum', models.IntegerField()),
                ('pduNum', models.IntegerField()),
                ('outputNum', models.IntegerField()),
                ('mac', models.CharField(max_length=20)),
                ('dateTime', models.DateTimeField(auto_now_add=True)),
                ('index', models.CharField(max_length=20)),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Co2Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rackNum', models.IntegerField()),
                ('pduNum', models.IntegerField()),
                ('outputNum', models.IntegerField()),
                ('mac', models.CharField(max_length=20)),
                ('dateTime', models.DateTimeField(auto_now_add=True)),
                ('ppm', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='HumidityData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rackNum', models.IntegerField()),
                ('pduNum', models.IntegerField()),
                ('outputNum', models.IntegerField()),
                ('mac', models.CharField(max_length=20)),
                ('dateTime', models.DateTimeField(auto_now_add=True)),
                ('rh', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='LightData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rackNum', models.IntegerField()),
                ('pduNum', models.IntegerField()),
                ('outputNum', models.IntegerField()),
                ('mac', models.CharField(max_length=20)),
                ('dateTime', models.DateTimeField(auto_now_add=True)),
                ('lux', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='MotorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rackNum', models.IntegerField()),
                ('pduNum', models.IntegerField()),
                ('outputNum', models.IntegerField()),
                ('mac', models.CharField(max_length=20)),
                ('dateTime', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rackNum', models.IntegerField()),
                ('pduNum', models.IntegerField()),
                ('outputNum', models.IntegerField()),
                ('mac', models.CharField(max_length=20)),
                ('sensorType', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TemperatureData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rackNum', models.IntegerField()),
                ('pduNum', models.IntegerField()),
                ('outputNum', models.IntegerField()),
                ('mac', models.CharField(max_length=20)),
                ('dateTime', models.DateTimeField(auto_now_add=True)),
                ('celsius', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
