# Generated by Django 3.2.3 on 2022-08-10 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('env', '0004_pdudata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PduData',
        ),
    ]
