# Generated by Django 3.2.3 on 2022-08-10 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('env', '0006_pdu_pdudata'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('racks', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rackNum', models.IntegerField()),
                ('pduNum', models.IntegerField()),
                ('outputNum', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('rackNum', models.IntegerField(primary_key=True, serialize=False)),
                ('deviceCount', models.IntegerField()),
                ('sensorCount', models.IntegerField()),
                ('pduCount', models.IntegerField()),
            ],
        ),
    ]
