# Generated by Django 3.2.3 on 2022-08-10 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('env', '0007_datacenter_device_rack'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CameraData',
        ),
        migrations.DeleteModel(
            name='Co2Data',
        ),
        migrations.DeleteModel(
            name='LightData',
        ),
        migrations.DeleteModel(
            name='MotorData',
        ),
    ]
