# Generated by Django 3.2.3 on 2022-08-11 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('env', '0008_auto_20220810_1537'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataCenter',
        ),
        migrations.DeleteModel(
            name='Device',
        ),
        migrations.DeleteModel(
            name='HumidityData',
        ),
        migrations.DeleteModel(
            name='Pdu',
        ),
        migrations.DeleteModel(
            name='PduData',
        ),
        migrations.DeleteModel(
            name='Rack',
        ),
        migrations.DeleteModel(
            name='Sensor',
        ),
        migrations.DeleteModel(
            name='TemperatureData',
        ),
    ]
