# Generated by Django 3.2.3 on 2022-08-11 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('env', '0009_auto_20220811_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pdu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pduNum', models.IntegerField()),
                ('outputCount', models.IntegerField()),
                ('ip', models.CharField(max_length=20)),
                ('info', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('rackNum', models.IntegerField(primary_key=True, serialize=False)),
                ('info', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pduOutput', models.IntegerField()),
                ('sensorNum', models.IntegerField()),
                ('mac', models.CharField(max_length=20)),
                ('sensorType', models.CharField(max_length=20)),
                ('info', models.CharField(max_length=200)),
                ('pdu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='env.pdu')),
                ('rack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='env.rack')),
            ],
        ),
        migrations.CreateModel(
            name='TemperatureData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTime', models.DateTimeField(auto_now_add=True)),
                ('celsius', models.DecimalField(decimal_places=2, max_digits=6)),
                ('pdu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='env.pdu')),
                ('rack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='env.rack')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='env.sensor')),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdu1Output', models.IntegerField()),
                ('pdu2Output', models.IntegerField()),
                ('serverNum', models.IntegerField()),
                ('info', models.CharField(max_length=200)),
                ('pdu1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdu1', to='env.pdu')),
                ('pdu2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdu2', to='env.pdu')),
                ('rack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='env.rack')),
            ],
        ),
        migrations.CreateModel(
            name='PduData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTime', models.DateTimeField(auto_now_add=True)),
                ('outputNum', models.IntegerField()),
                ('current', models.DecimalField(decimal_places=2, max_digits=20)),
                ('power', models.DecimalField(decimal_places=2, max_digits=20)),
                ('energyCounter', models.DecimalField(decimal_places=2, max_digits=20)),
                ('tpf', models.DecimalField(decimal_places=2, max_digits=20)),
                ('phaseShift', models.DecimalField(decimal_places=2, max_digits=20)),
                ('reverseEnergyCounter', models.DecimalField(decimal_places=2, max_digits=20)),
                ('pdu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='env.pdu')),
                ('rack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='env.rack')),
            ],
        ),
        migrations.AddField(
            model_name='pdu',
            name='rack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='env.rack'),
        ),
        migrations.CreateModel(
            name='HumidityData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTime', models.DateTimeField(auto_now_add=True)),
                ('rh', models.DecimalField(decimal_places=2, max_digits=6)),
                ('pdu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='env.pdu')),
                ('rack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='env.rack')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='env.sensor')),
            ],
        ),
    ]
