# Generated by Django 3.2.3 on 2022-08-11 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('env', '0010_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTime', models.DateTimeField(auto_now_add=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=6)),
                ('pdu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='env.pdu')),
                ('rack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='env.rack')),
            ],
        ),
        migrations.RemoveField(
            model_name='temperaturedata',
            name='pdu',
        ),
        migrations.RemoveField(
            model_name='temperaturedata',
            name='rack',
        ),
        migrations.RemoveField(
            model_name='temperaturedata',
            name='sensor',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='sensorType',
        ),
        migrations.DeleteModel(
            name='HumidityData',
        ),
        migrations.DeleteModel(
            name='TemperatureData',
        ),
        migrations.AddField(
            model_name='sensordata',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='env.sensor'),
        ),
    ]
