# Generated by Django 3.2.3 on 2022-08-11 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('env', '0011_auto_20220811_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='dataType',
            field=models.CharField(choices=[('humidity', 'Humidity')], default='temperature', max_length=20),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='dataUnit',
            field=models.CharField(choices=[('rh', 'Rh')], default='temperature', max_length=20),
        ),
    ]
