# Generated by Django 3.2.3 on 2022-08-11 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('env', '0012_auto_20220811_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordata',
            name='dataType',
            field=models.CharField(choices=[('humidity', 'Humidity')], default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='dataUnit',
            field=models.CharField(choices=[('rh', 'Rh')], default=0, max_length=20),
        ),
    ]
