# Generated by Django 3.2.3 on 2022-08-11 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('env', '0013_auto_20220811_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordata',
            name='dataType',
            field=models.CharField(choices=[('temperature', 'temperature'), ('humidity', 'humidity')], default='temperature', max_length=20),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='dataUnit',
            field=models.CharField(choices=[('celsius', 'celsius'), ('rh', 'rh')], default='celsius', max_length=20),
        ),
    ]
