# Generated by Django 3.2.3 on 2022-08-16 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('env', '0014_auto_20220811_1700'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='pdu',
            constraint=models.UniqueConstraint(fields=('rack', 'pduNum'), name='rack_pdu'),
        ),
        migrations.AddConstraint(
            model_name='sensor',
            constraint=models.UniqueConstraint(fields=('rack', 'sensorNum'), name='rack_sensor'),
        ),
        migrations.AddConstraint(
            model_name='server',
            constraint=models.UniqueConstraint(fields=('rack', 'serverNum'), name='rack_server'),
        ),
    ]
