# Generated by Django 3.2.3 on 2022-08-08 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StoredPduData',
        ),
    ]
